//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class doctor_Register
    {
        [Required(ErrorMessage = "This Feild is required.")]
        public string first_Name { get; set; }

        [Required(ErrorMessage = "This Feild is required.")]
        public string last_Name { get; set; }

        [Display(Name = "Mobile Number:")]
        [Required(ErrorMessage = "Mobile Number is required.")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public long mob_Number { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This Feild is required.")]
        public string password { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Confirmation Password is required.")]
        [Compare("password", ErrorMessage = "Password and Confirmation Password must match.")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "This Feild is required.")]
        public string specilization { get; set; }

        [Required(ErrorMessage = "This Feild is required.")]
        public string gender { get; set; }

        [Required(ErrorMessage = "This Feild is required.")]
        public string city { get; set; }
        [Required(ErrorMessage = "This Feild is required.")]
        public string email { get; set; }

        [Required(ErrorMessage = "This Feild is required.")]
        public int license_Number { get; set; }

        [Required(ErrorMessage = "This Feild is required.")]
        public int cost { get; set; }
    }
}
